eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8763
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/market_microservice?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0


# mybatis配置
mybatis:
  type-aliases-package: com.kermi.market.userservice.mapper
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.kermi.market.userservice.mapper: debug

