eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: feignservice
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
#feign:
#  hystrix:
#    enabled: true